---
title: "Football Exploratory Analysis"
output:
  html_document: default
  html_notebook: default
---

```{r}
source("readDataToMemory.R")
readFootball()

library(ggplot2)
library(ggthemes)

print(dbListTables(sql_con))
```

## Pipes

```{r}
head(players)

#equivalent
players %>%
  head
```

```{r}
players %>%
  colnames
```

```{r}
sapply(players, class)

#equivalent
players %>%
  sapply(class)

#equivalent
class %>%
  sapply(players, .)
```



## SELECT ~ select

```{r}
players %>%
  head %>%
  select(player_name, birthday)
```

```{r}
dbGetQuery(sql_con, "
SELECT player_name, birthday
FROM Player
LIMIT 6")
```

## WHERE ~ filter

```{r}
players %>%
  filter(birthday >= "1998") %>%
  head
```

```{r}
dbGetQuery(sql_con, "
SELECT *
FROM Player
WHERE birthday >= 1998
LIMIT 6")
```


## ORDER ~ arrange

```{r}
players %>%
  arrange(birthday) %>%
  head
```

```{r}
dbGetQuery(sql_con, "
SELECT *
FROM Player
ORDER BY birthday
LIMIT 6")
```

## aggregators ~ summarise

```{r}
players %>%
  summarise(weight=mean(weight), height=mean(height))
```

```{r}
dbGetQuery(sql_con, "
SELECT AVG(weight) AS weight, AVG(height) AS height
FROM Player")
```


## mutate

```{r}
players %>%
  mutate(weight_kg = weight*0.45359237) %>%
  summarise(weight=mean(weight_kg), height=mean(height))
```

```{r}
dbGetQuery(sql_con, "
SELECT avg(weight*0.45359237) as weight, avg(height) as height
FROM Player")
```

```{r}
#També podríem fer la query així:
"SELECT avg(weight*0.45359237) as weight, avg(height) as height FROM Player" %>%
  dbGetQuery(sql_con, .)
```

## GROUP BY

```{r}
players %>%
  mutate(year=as.numeric(substring(birthday, 1, 4))) %>% #agafem només l'any
  group_by(year) %>%
  summarise(height=mean(height)) %>%
  ggplot(aes(year, height)) +
  geom_line(colour="darkorange") +
  theme_minimal()
```

```{r}
players %>%
  mutate(year=as.numeric(substring(birthday, 1, 4))) %>%
  group_by(year) %>%
  summarise(nsample=n()) %>% #mirem el nombre de dades que tenim a cada any
  ggplot(aes(year, nsample)) +
  geom_line(colour="darkorange") +
  theme_minimal()
```

```{r}
players %>%
  mutate(year=as.numeric(substring(birthday, 1, 4))) %>%
  group_by(year) %>%
  summarise(height=mean(height), nsamples=n()) %>%
  filter(nsamples >= 200) %>%
  ggplot(aes(year, height)) +
  geom_line(colour="darkorange") +
  theme_minimal()
```

Passem a SQL:

```{r}
data <- dbGetQuery(sql_con, "
          SELECT SUBSTR(birthday,1,4) as year, avg(height) AS height, count(*) as nsamples
          FROM Player
          GROUP BY SUBSTR(birthday,1,4)
          HAVING COUNT(*)>=200")

ggplot(data, aes(as.numeric(year), height)) +
  geom_line(colour="darkorange") +
  theme_minimal()
```


Exercise

* Translate from SQL to dply or from dply to SQL

```{r}
dbGetQuery(sql_con, "
SELECT *
FROM Match
LIMIT 6
")

games %>%
  head
```


```{r}
dbGetQuery(sql_con, "
SELECT country_id
,   COUNT(1) AS n
FROM Match
GROUP BY country_id
ORDER BY n DESC
")

games %>%
  group_by(country_id) %>%
  summarise(n = n()) %>%
  arrange(desc(n))
```


```{r}
countries
```


```{r}
games %>%
  left_join(countries, by=c("country_id" = "id")) %>%
  select(name, home_team_api_id) %>%
  group_by(name) %>%
  summarise(teams = n_distinct(home_team_api_id)) %>%
  arrange(desc(teams))

dbGetQuery(sql_con, "
SELECT name, count(distinct home_team_api_id)
FROM Match t1 INNER JOIN Country t2 ON  t1.country_id=t2.id
GROUP BY name
ORDER BY count(distinct home_team_api_id) DESC")
```


```{r}
dbGetQuery(sql_con, "
SELECT *
FROM Player_Attributes
LIMIT 6
")

players_atr <- tbl_df(dbGetQuery(sql_con,"SELECT * FROM Player_Attributes"))
players_atr %>%
  head
```


* From where do players with higest accuracy come from?
```{r}
players_atr %>%
  select(player_api_id, heading_accuracy) %>%
  summarise(max = max(heading_accuracy, na.rm=T))
```


* Add team name and translate to dplyr

```{r}
dbGetQuery(sql_con, "
SELECT stage, home_team_api_id, home_team_goal
FROM Match
WHERE country_id = 1
AND season = '2008/2009'
ORDER BY stage
")
```
