---
title: "Instacart Recommender"
output: html_notebook
---

```{r}
source("readDataToMemory.R")
readInstacart()

library(DBI)
library(ggplot2)
library(ggthemes)

src_tbls(sc)
```

```{r}
order_products__prior %>%
  select(order_id, product_id) %>%
  left_join(orders, by="order_id") %>%
  filter(user_id <= 10) %>% 
  select(product_id, user_id) %>%
  group_by(user_id, product_id) %>%
  summarise(rating = n()) %>%
  rename(user = user_id) %>%
  mutate(item=product_id) %>%
  select(user, item, rating) ->
  user_item_rating
```


```{r}
user_item_rating
```


```{r}
explicit_model <- ml_als_factorization( user_item_rating, iter.max = 5, regularization.parameter = 0.01)
```

```{r}
explicit_model
```


```{r}
#matriu amb files=productes
V <- as.matrix(explicit_model$item.factors)

#matriu amb files=individus
U <- as.matrix(explicit_model$user.factors)

#multipliquem matrius
A <- U %*% t(V)
apply(A, 1, which.max)
```

```{r}
order_products__prior %>%
  colnames %>%
  print

orders %>%
  colnames %>%
  print
```

1. Fer consultes com les q ja hem fet per instacart
2. At least 1 plot and 1 window function.
